[package]
name = "praxfetch"
version = "0.1.0"
edition = "2021"
description = "Fast, zero-subprocess Linux system information fetch tool written in Rust."
license = "MIT"
repository = "https://github.com/Praxis1071/praxfetch"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
colored = "3.1.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
